using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using System.Web.Script.Serialization;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;

namespace Marvilon.K01.DrawingsV3 {
 class PathsCfg { public string candidate_dir{get;set;} public string drawing_dir{get;set;} public string report_dir{get;set;} }
 class GateCfg { public PathsCfg paths{get;set;} }
 class Metrics { public string drawing_no=""; public string model=""; public string slddrw=""; public string pdf=""; public int view_count=0; public int marked_dimensions=0; public bool section=false; public bool end=false; public bool iso=false; public bool title=false; public bool characteristic_table=false; public string semantic_spec=""; public string status="RUNNING"; public List<string> warnings=new List<string>(); }
 class Report { public string schema="k01_gate04d_c2r1_drawings_v3_tpd"; public string created_utc=DateTime.UtcNow.ToString("o"); public string status="RUNNING"; public string solidworks_revision=""; public string policy="INTENT_DRIVEN_NO_AUTODIM"; public Metrics p003=new Metrics(); public Metrics p007=new Metrics(); public List<string> warnings=new List<string>(); public string error=""; }
 class Program {
  static SldWorks sw; static GateCfg cfg; static Report rep=new Report(); static string root,reportPath;
  static int Main(){try{root=FindRoot();cfg=new JavaScriptSerializer().Deserialize<GateCfg>(File.ReadAllText(Path.Combine(root,"K01_GATE04D_C2R1_PARAMS_v1.json")));Directory.CreateDirectory(cfg.paths.drawing_dir);Directory.CreateDirectory(cfg.paths.report_dir);Connect();rep.p003=Make("K01-D-003","K01-P-003","Cartridge Body",Path.Combine(cfg.paths.candidate_dir,"K01-P-003_Cartridge_Body_GATE04D_C2R1_CANDIDATE.SLDPRT"),"K01-D-003_P003_DRAWING_INTENT_v1.json",P003());rep.p007=Make("K01-D-006","K01-P-007","Hermetic Magnetic Can",Path.Combine(cfg.paths.candidate_dir,"K01-P-007_Hermetic_Magnetic_Can_GATE04D_C2R1_CANDIDATE.SLDPRT"),"K01-D-006_P007_DRAWING_INTENT_v1.json",P007());rep.status=(rep.p003.status=="PASS_NATIVE_DRAFT"&&rep.p007.status=="PASS_NATIVE_DRAFT")?"PASS_NATIVE_DRAFT":"HOLD_DRAWING_QUALITY";Save();return rep.status.StartsWith("PASS")?0:2;}catch(Exception ex){rep.status="FAIL";rep.error=ex.ToString();try{Save();}catch{}Console.Error.WriteLine(ex);return 1;}}
  static string[,] P003(){return new string[,]{{"ID","RELEASE CHARACTERISTIC","SPEC / TOLERANCE"},{"C01","J2 FACE / DATUM A","FLATNESS 0.03; Rq ≤0.4 µm"},{"C02","PILOT OD","Ø14.10 g6 ×1.50"},{"C03","PILOT AXIS / DATUM B","PERP Ø0.03 TO A"},{"C04","PILOT CLEARANCE ID","Ø12 H9"},{"C05","O-RING GLAND","ID16.00; W2.10 +0.10/0; D1.10 +0.05/0"},{"C06","THREAD PATTERN","3×M2.5×0.45-6H; PCD26.50 BASIC; 120° BASIC; POS Ø0.10 |A|B"},{"C07","FLANGE OD","Ø33.00 ±0.05"},{"C08","MATERIAL","AISI 316L / EN 1.4404"}};}
  static string[,] P007(){return new string[,]{{"ID","RELEASE CHARACTERISTIC","SPEC / TOLERANCE"},{"C01","J2 FACE / DATUM A","FLATNESS 0.03"},{"C02","LOCATOR / DATUM B","Ø14.10 H7 ×1.70"},{"C03","LOCATOR AXIS","PERP Ø0.03 TO A"},{"C04","CLEARANCE PATTERN","3×Ø2.90 THRU; PCD26.50 BASIC; 120° BASIC; POS Ø0.15 |A|B"},{"C05","FLANGE","Ø33.00 ±0.05 ×3.00 ±0.05"},{"C06","OVERALL LENGTH","35.00 ±0.05"},{"C07","THIN CAN OD","Ø10.00 — NATIVE MODEL CONTROL"},{"C08","THIN CAN ID","Ø9.40 — NATIVE MODEL CONTROL"},{"C09","MATERIAL","AISI 316L / EN 1.4404"}};}
  static Metrics Make(string dwg,string part,string desc,string modelPath,string specName,string[,] tab){if(!File.Exists(modelPath))throw new Exception("Missing model "+modelPath);Metrics m=new Metrics();m.drawing_no=dwg;m.model=modelPath;m.semantic_spec=Path.Combine(@"D:\BreshevEngineering\marvilon-k01","control","drawings","spec",specName);int e=0,w=0;ModelDoc2 model=sw.OpenDoc6(modelPath,(int)swDocumentTypes_e.swDocPART,(int)swOpenDocOptions_e.swOpenDocOptions_Silent,"",ref e,ref w) as ModelDoc2;if(model==null)throw new Exception("Open failed "+modelPath);string mt=model.GetTitle();try{string templ=sw.GetUserPreferenceStringValue((int)swUserPreferenceStringValue_e.swDefaultTemplateDrawing);if(String.IsNullOrWhiteSpace(templ)||!File.Exists(templ))throw new Exception("Default drawing template missing");ModelDoc2 dm=sw.NewDocument(templ,0,0,0) as ModelDoc2;if(dm==null)throw new Exception("New drawing failed");string dt=dm.GetTitle();try{DrawingDoc dr=dm as DrawingDoc;dr.SetupSheet5("Sheet1",(int)swDwgPaperSizes_e.swDwgPaperA3size,(int)swDwgTemplates_e.swDwgTemplateA3size,2,1,true,"",0.420,0.297,"",false);try{dm.Extension.SetUserPreferenceToggle((int)swUserPreferenceToggle_e.swDetailingOrthoView_AddViewLabelOnViewCreation,(int)swUserPreferenceOption_e.swDetailingNoOptionSpecified,false);}catch{}
    View basev=dr.CreateDrawViewFromModelView3(modelPath,"*Front",0.125,0.215,0);View end=dr.CreateDrawViewFromModelView3(modelPath,"*Right",0.315,0.215,0);View iso=dr.CreateDrawViewFromModelView3(modelPath,"*Isometric",0.320,0.105,0);m.end=end!=null;m.iso=iso!=null;if(basev==null||end==null)throw new Exception("required views failed");
    try{dr.ActivateView(basev.Name);double[] o=(double[])basev.GetOutline();double cy=(o[1]+o[3])*0.5;dm.ClearSelection2(true);SketchSegment ln=dm.SketchManager.CreateLine(o[0]-0.003,cy,0,o[2]+0.003,cy,0);if(ln!=null){View sec=dr.CreateSectionViewAt5(0.125,0.105,0,"A",32,null,0);m.section=sec!=null;}}catch(Exception ex){m.warnings.Add("section: "+ex.Message);}
    try{dr.ActivateView(basev.Name);dr.InsertModelAnnotations3((int)swImportModelItemsSource_e.swImportModelItemsFromEntireModel,(int)swInsertAnnotation_e.swInsertDimensionsMarkedForDrawing,true,false,false,false);}catch(Exception ex){m.warnings.Add("marked dims: "+ex.Message);}
    dm.ForceRebuild3(false);m.marked_dimensions=CountDims(dr);m.view_count=CountViews(dr);
    try{TableAnnotation t=dm.Extension.InsertGeneralTableAnnotation(false,0.215,0.286,0,"",tab.GetLength(0),tab.GetLength(1));if(t!=null){for(int r=0;r<tab.GetLength(0);r++)for(int c=0;c<tab.GetLength(1);c++)t.set_Text2(r,c,false,tab[r,c]);m.characteristic_table=true;}}catch(Exception ex){m.warnings.Add("characteristic table: "+ex.Message);}
    try{string[,] tb={{"DRAWING",dwg,"PART",part},{"TITLE",desc,"STATUS","DRAFT / NOT RELEASED"},{"PROJECTION","FIRST ANGLE","UNITS","mm"},{"GEOMETRY","NATIVE SW MODEL","REV","C2R1-PR1"}};TableAnnotation t=dm.Extension.InsertGeneralTableAnnotation(false,0.265,0.050,0,"",4,4);if(t!=null){for(int r=0;r<4;r++)for(int c=0;c<4;c++)t.set_Text2(r,c,false,tb[r,c]);m.title=true;}}catch(Exception ex){m.warnings.Add("title: "+ex.Message);}
    try{Note n=dm.InsertNote("MODEL-BASED NOMINAL GEOMETRY. DO NOT SCALE. RELEASE CHARACTERISTICS ARE IDENTIFIED IN THE CONTROLLED TABLE AND DRAWING-INTENT SPEC. NO AUTODIMENSIONING USED.") as Note;if(n!=null){Annotation a=n.GetAnnotation() as Annotation;if(a!=null)a.SetPosition2(0.015,0.025,0);}}catch{}
    dm.ForceRebuild3(false);string stem=dwg+"_"+part+"_C2R1_TPD_V3";m.slddrw=Path.Combine(cfg.paths.drawing_dir,stem+".SLDDRW");m.pdf=Path.Combine(cfg.paths.drawing_dir,stem+".PDF");SaveAs(dm,m.slddrw);SaveAs(dm,m.pdf);bool semantic=File.Exists(m.semantic_spec);bool views=m.view_count>=3&&m.section&&m.end&&m.iso;bool content=m.characteristic_table&&m.title&&m.marked_dimensions>=1&&m.marked_dimensions<=24;m.status=(semantic&&views&&content)?"PASS_NATIVE_DRAFT":"HOLD_DRAWING_QUALITY";return m;}finally{try{sw.CloseDoc(dt);}catch{}}}finally{try{sw.CloseDoc(mt);}catch{}}}
  static int CountViews(DrawingDoc d){int n=0;View v=d.GetFirstView() as View;if(v!=null)v=v.GetNextView() as View;while(v!=null){n++;v=v.GetNextView() as View;}return n;}
  static int CountDims(DrawingDoc d){int n=0;View v=d.GetFirstView() as View;if(v!=null)v=v.GetNextView() as View;while(v!=null){try{n+=v.GetDisplayDimensionCount();}catch{}v=v.GetNextView() as View;}return n;}
  static void SaveAs(ModelDoc2 d,string p){Directory.CreateDirectory(Path.GetDirectoryName(p));int s=d.SaveAs3(p,0,0);if(s!=0||!File.Exists(p))throw new Exception("SaveAs3 failed "+s+" "+p);}
  static void Connect(){object o=null;try{o=Marshal.GetActiveObject("SldWorks.Application");}catch{}sw=o!=null?(SldWorks)o:(SldWorks)Activator.CreateInstance(Type.GetTypeFromProgID("SldWorks.Application",true));sw.Visible=true;rep.solidworks_revision=sw.RevisionNumber();}
  static string FindRoot(){string x=AppDomain.CurrentDomain.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar);for(int i=0;i<4;i++){if(File.Exists(Path.Combine(x,"K01_GATE04D_C2R1_PARAMS_v1.json")))return x;DirectoryInfo p=Directory.GetParent(x);if(p==null)break;x=p.FullName;}throw new Exception("params not found");}
  static void Save(){if(cfg!=null&&cfg.paths!=null)reportPath=Path.Combine(cfg.paths.report_dir,"K01_GATE04D_C2R1_TYPED_DRAWINGS_V3.json");else reportPath=Path.Combine(root??".","K01_GATE04D_C2R1_TYPED_DRAWINGS_V3.json");File.WriteAllText(reportPath,new JavaScriptSerializer().Serialize(rep));}
 }
}
