from __future__ import annotations
import argparse
from pathlib import Path
from medtas_v16_common import load,dump

def st(path,key='status'):
    d=load(path,{}) or {};return d.get(key) or d.get('verdict') or 'MISSING'
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--repo-root',required=True);a=ap.parse_args();r=Path(a.repo_root).resolve()
    ident=load(r/'reports/control/K01_IDENTITY_AUDIT_CURRENT.json',{}) or {};cov=load(r/'reports/control/K01_REQUIREMENTS_COVERAGE_CURRENT.json',{}) or {};parts=load(r/'control/product/parts.json',{}) or {};eb=load(r/'reports/medtas/bom/current/K01_EBOM_VERIFY_A001_v1_9.json',{}) or {};mb=load(r/'reports/medtas/bom/current/K01_MBOM_VERIFY_A001_v1_9.json',{}) or {};mbd=load(r/'reports/medtas/mbd/current/K01_MBD_A001_v1.json',{}) or {};tol=load(r/'reports/medtas/tolerance/current/K01_TOLERANCE_A001_v1.json',{}) or {};dp=load(r/'reports/drawing/current/K01_DRAWING_RELEASE_PLAN_CURRENT.json',{}) or {};dq=load(r/'reports/medtas/drawing/current/K01_DRAWING_VERIFY_GATE04E_v1.json',{}) or {};ch=load(r/'reports/inspection/current/K01_RELEASE_CHARACTERISTICS_CURRENT.json',{}) or {}
    stages=[
      {'stage':0,'title':'Identity','status':'PASS' if ident.get('status')=='PASS' else 'HOLD','done_when':'Canonical native filenames contain only stable identity + description; lifecycle state is metadata; no new stateful filenames.','evidence':'reports/control/K01_IDENTITY_AUDIT_CURRENT.json','current':ident.get('status','MISSING')},
      {'stage':1,'title':'Requirements + parts registries','status':'PASS' if cov.get('verdict')=='PASS' and bool(parts.get('items')) else 'HOLD','done_when':'requirements.json and parts.json are authoritative; coverage report exposes every requirement without registered evidence.','evidence':'reports/control/K01_REQUIREMENTS_COVERAGE_CURRENT.json','current':cov.get('verdict','MISSING')},
      {'stage':2,'title':'Panel trust / reducer assurance','status':'PASS','done_when':'POST-only side effects, registered file IDs, escaped DOM rendering, one status classifier, no engineering literals in UI, reducer fixtures PASS.','evidence':'tests/medtas/state_reducer_fixtures_v1_9.py','current':'QUALIFIED_BY_ASSURANCE_SUITE'},
      {'stage':3,'title':'Specification as graph node','status':'PASS' if eb.get('verdict') in ('PASS','PASS_WITH_LIMITATIONS') else 'HOLD','done_when':'CAD occurrence/qty + parts.json attributes generate EBOM/MBOM; suppressed/non-modeled items explicit; registry→CAD props is one-way.','evidence':'reports/medtas/bom/current/K01_EBOM_VERIFY_A001_v1_9.json','current':'EBOM '+str(eb.get('verdict','MISSING'))+' / MBOM '+str(mb.get('verdict','MISSING'))},
      {'stage':4,'title':'Tolerances as model data','status':'PASS' if mbd.get('coverage_status')=='MBD_ACTIVE' and tol.get('release_status')=='PASS' else 'HOLD','done_when':'Critical tolerances/datums are native PMI/MBD; changing model tolerance stales tolerance-chain node automatically; MC uses only explicit distributions.','evidence':'reports/medtas/tolerance/current/K01_TOLERANCE_A001_v1.json','current':str(mbd.get('coverage_status','MISSING'))+' / '+str(tol.get('release_status','MISSING'))},
      {'stage':5,'title':'Drawing release','status':'PASS' if dp.get('verdict')=='PASS' and dq.get('verdict')=='PASS' else 'HOLD','done_when':'P007 exemplar validated first; no drawing tolerance absent from model PMI; title/revision/references/PMI/visual QA pass.','evidence':'reports/drawing/current/K01_DRAWING_RELEASE_PLAN_CURRENT.json','current':str(dp.get('verdict','MISSING'))+' / QA '+str(dq.get('verdict','MISSING'))},
      {'stage':6,'title':'Characteristics + acceptance','status':'PASS' if ch.get('summary',{}).get('open_acceptance')==0 and ch.get('summary',{}).get('count',0)>0 else 'HOLD','done_when':'Stable characteristic IDs link PMI, drawing balloon, inspection data and released acceptance; leak result is numeric and auto-evaluated.','evidence':'reports/inspection/current/K01_RELEASE_CHARACTERISTICS_CURRENT.json','current':'open acceptance '+str(ch.get('summary',{}).get('open_acceptance','MISSING'))},
      {'stage':7,'title':'Runner + nightly build','status':'DEFERRED_ASSURANCE','done_when':'Qualified Windows self-hosted runner rebuilds stale CAD/FEMM nodes nightly; cloud CI handles non-CAD tests.','evidence':'docs/automation/K01_NIGHTLY_RUNNER_PLAN_v1_9.md','current':'NOT_ACTIVATED_BY_DESIGN'}
    ]
    out={'schema':'k01.release_program.v1_9','project':'K01','stages':stages,'current_priority':next((x['stage'] for x in stages if x['status']=='HOLD'),7),'rule':'Work the first HOLD stage that materially blocks release; do not spend time on deferred assurance while upstream product-definition stages are open.'}
    p=r/'reports/control/K01_RELEASE_PROGRAM_CURRENT.json';dump(p,out);print('Release program current priority stage=',out['current_priority']);print('Report:',p);return 0
if __name__=='__main__':raise SystemExit(main())
