from __future__ import annotations
import argparse
from pathlib import Path
from medtas_v16_common import load,dump,register_build,register_verify

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--repo-root',required=True);a=ap.parse_args();r=Path(a.repo_root).resolve();pdp=r/'reports/medtas/product_definition/current/K01_PRODUCT_DEFINITION_GATE04E_v1_8.json';out=r/'reports/drawing/current/K01_DRAWING_RELEASE_PLAN_CURRENT.json';pd=load(pdp,{}) or {};bind=load(r/'control/medtas/v1/bindings/K01_DRAWING_GENERATION_BINDING_v1_7.json',{}) or {};template=bind.get('template_path');rows=[];ready=[];block=[]
    if not template or not Path(str(template)).exists():block.append('DRAWING-TEMPLATE-BINDING')
    for d in pd.get('drawings',[]) or []:
        dr={'drawing_no':d.get('drawing_no'),'model':d.get('model'),'title':d.get('title'),'characteristics':[],'blocking_items':[]}
        for c in d.get('characteristics',[]) or []:
            st=c.get('drawing_release_authority') or 'MISSING';x={'id':c.get('id'),'role':c.get('role'),'authority':c.get('authority'),'definition_state':c.get('definition_state'),'drawing_release_authority':st,'source':c.get('source'),'evidence':c.get('evidence',{}),'tolerance_release_state':c.get('tolerance_release_state')};dr['characteristics'].append(x)
            if st!='READY':dr['blocking_items'].append(c.get('id'))
        if not template or not Path(str(template)).exists():dr['blocking_items'].append('DRAWING-TEMPLATE-BINDING')
        dr['status']='READY_FOR_NATIVE_GENERATION' if not dr['blocking_items'] else 'BLOCKED_PRODUCT_DEFINITION'
        if dr['status']=='READY_FOR_NATIVE_GENERATION':ready.append(dr['drawing_no'])
        else:block.extend(dr['blocking_items'])
        rows.append(dr)
    # P007 is the priority exemplar, but it does not bypass strict MBD requirements.
    p007=load(r/'reports/drawing/current/K01-D-006_P007_EXEMPLAR_PLAN_CURRENT.json',{}) or {}
    verdict='PASS' if rows and len(ready)==len(rows) else 'PASS_WITH_LIMITATIONS' if ready else 'HOLD'
    payload={'schema':'k01.drawing_release_plan.gate04e.v1_9','verdict':verdict,'drawings':rows,'generation_binding':bind,'ready_drawings':ready,'blocking_items':sorted(set(block)),'priority_exemplar':{'drawing_no':'K01-D-006','status':p007.get('status','MISSING'),'blocking_items':p007.get('blocking_items',[])},'native_artifact_status':'READY_PARTIAL' if ready and verdict!='PASS' else 'READY' if verdict=='PASS' else 'NOT_GENERATED','policy':'Drawing skeleton/views may be generated by API, but any dimensional/GD&T/tolerance content released on a drawing must originate from model PMI/MBD. AutoDimension and independent hand-typed duplicate tolerances are prohibited.'};dump(out,payload);register_build(r,'K01.DRAWING.RELEASE.PLAN.GATE04E',{'tool':'build_drawing_release_plan_v1_9.py'});register_verify(r,'K01.DRAWING.RELEASE.PLAN.GATE04E',verdict,metrics={'drawings':len(rows),'ready_drawings':len(ready),'blocking_items':len(set(block))},limitations=[] if verdict=='PASS' else sorted(set(block)));print('Drawing release plan:',verdict,'ready=',ready,'blockers=',len(set(block)));return 0
if __name__=='__main__':raise SystemExit(main())
