from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from medtas_v16_common import load,dump,register_build,register_verify

def artifact_hash(art):
    rows=sorted((x.get('drawing_no'),x.get('kind'),x.get('sha256')) for x in art.get('artifacts',[]) or [])
    return hashlib.sha256(json.dumps(rows,ensure_ascii=False,separators=(',',':')).encode()).hexdigest()

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--repo-root',required=True);a=ap.parse_args();r=Path(a.repo_root).resolve()
    plan=load(r/'reports/drawing/current/K01_DRAWING_RELEASE_PLAN_CURRENT.json',{}) or {};art=load(r/'reports/medtas/drawing/current/K01_DRAWING_ARTIFACT_GATE04E_v1_8.json',{}) or {};raw=load(r/'reports/medtas/drawing/current/K01_DRAWING_NATIVE_QA_RAW_v1_9.json',{}) or {};policy=load(r/'control/drawings/K01_DRAWING_QA_POLICY_v1_9.json',{}) or {};parts=load(r/'control/product/parts.json',{}) or {};mbd=load(r/'reports/medtas/mbd/current/K01_MBD_A001_v1.json',{}) or {}
    issues=[];ready=set(plan.get('ready_drawings',[]) or []);generated={x.get('drawing_no') for x in art.get('artifacts',[]) or [] if x.get('kind')=='SLDDRW'}
    for dn in sorted(ready-generated):issues.append('DQA-001:MISSING_NATIVE_DRAWING:'+dn)
    # Semantic readback is mandatory once native drawings exist. The file is generated by the future/native readback adapter; absence is fail-closed.
    if generated and not raw:issues.append('DQA-RAW-001:NATIVE_DRAWING_SEMANTIC_READBACK_MISSING')
    for x in raw.get('drawings',[]) or []:
        dn=x.get('drawing_no') or 'UNKNOWN'
        checks=x.get('checks',{}) or {}
        for cid in ('DQA-002','DQA-003','DQA-004','DQA-005','DQA-006','DQA-007','DQA-008'):
            if checks.get(cid) is not True:issues.append(cid+':'+dn)
    ah=artifact_hash(art);vis=load(r/'reports/medtas/drawing/current/K01_DRAWING_VISUAL_APPROVAL_GATE04E_v1_8.json',{}) or load(r/'reports/medtas/drawing/current/K01_DRAWING_VISUAL_APPROVAL_GATE04E_v1_7.json',{}) or {}
    visual_ok=bool(generated) and str(vis.get('verdict','')).upper()=='PASS' and vis.get('artifact_set_hash')==ah
    if generated and not visual_ok:issues.append('DQA-009:VISUAL_QA_MISSING_OR_STALE')
    full=bool(plan.get('drawings')) and plan.get('verdict')=='PASS' and art.get('status')=='PASS' and raw and not issues
    verdict='PASS' if full else 'HOLD'
    payload={'schema':'k01.drawing_qa.gate04e.v1_9','verdict':verdict,'issues':sorted(set(issues)),'metrics':{'definition_ready':len(ready),'native_generated':len(generated),'native_readback_drawings':len(raw.get('drawings',[]) or []),'visual_current':visual_ok,'artifact_set_hash':ah},'policy':policy,'parts_registry_loaded':bool(parts.get('items')),'mbd_loaded':bool(mbd.get('documents')),'note':'This gate is fail-closed. Native drawing semantic readback must prove title-block/revision/reference/tolerance/PMI/balloon parity before release.'}
    out=r/'reports/medtas/drawing/current/K01_DRAWING_VERIFY_GATE04E_v1.json';dump(out,payload);register_build(r,'K01.DRAWING.VERIFY.GATE04E',{'tool':'drawing_qa_gate_v1_9.py'});register_verify(r,'K01.DRAWING.VERIFY.GATE04E',verdict,metrics=payload['metrics'],limitations=payload['issues']);print(verdict,'drawing QA gate');[print(' -',x) for x in payload['issues']];return 0 if verdict=='PASS' else 1
if __name__=='__main__':raise SystemExit(main())
