from __future__ import annotations
import argparse,datetime as dt,json,subprocess,sys
from pathlib import Path
R=Path(r"D:\BreshevEngineering\marvilon-k01")
P={"pd":Path("control/product_definition/K01-P-004_PRODUCT_DEFINITION_CURRENT.json"),"read":Path("reports/product_definition/K01-P-004_READINESS_CURRENT.json"),"tf":Path("reports/engineering/K01_P004_TECHNICAL_FILTER_CURRENT.json"),"ex":Path("control/drawings/K01_DRAWING_EXEMPLAR_POLICY_CURRENT.json"),"edr":Path("control/decisions/EDR-042_P004_DATUM_GPS_SURFACE_INSPECTION_ARCHITECTURE.json"),"rep":Path("reports/engineering/K01_P004_DATUM_GPS_SURFACE_INSPECTION_CURRENT.json"),"insp":Path("reports/inspection/K01-P-004_INSPECTION_PLAN_CURRENT.json"),"next":Path("control/project/K01_NEXT_ACTIONS_CURRENT.json"),"gate":Path("control/project/K01_ACTIVE_STEP_GATE.json"),"front":Path("control/state/K01_COMPLETION_FRONTIER_CURRENT.json"),"center":Path("control/center/K01_CENTER_MASTER_FEED_CURRENT.json")}
def rd(p,d=None):
 try:return json.loads(p.read_text(encoding='utf-8-sig'))
 except:return d
def wr(p,o):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(o,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
def now():return dt.datetime.now(dt.timezone.utc).isoformat()
def guards(repo):
 for t in ('k01_temporal_coherence_guard_v1.py','k01_semantic_coherence_guard_v1.py'):
  if subprocess.run([sys.executable,'tools/state/'+t,'--repo-root',str(repo),'--write-report'],cwd=repo).returncode: raise SystemExit('HOLD: state guard failed')
def setc(pd,cid,u):
 xs=pd.setdefault('characteristics',[])
 for c in xs:
  if isinstance(c,dict) and c.get('id')==cid:c.update(u);return
 x={'id':cid};x.update(u);xs.append(x)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--repo-root',default=str(R));a=ap.parse_args();repo=Path(a.repo_root);guards(repo)
 for k in ('pd','read','ex','next','gate','front'):
  if not (repo/P[k]).is_file():raise SystemExit('HOLD: missing '+str(P[k]))
 n=rd(repo/P['next'],{}) or {}
 if n.get('next_action_id')!='K01-NA-P004-DATUM-GPS-SURFACE-INSPECTION':raise SystemExit('HOLD: frontier not at P004 datum/GPS/surface/inspection')
 ex=rd(repo/P['ex'],{}) or {}
 rep={"schema":"k01.p004.datum_gps_surface_inspection.current.v1","generated_utc":now(),"status":"PASS_ARCHITECTURE_DEFINED__NUMERIC_ACCEPTANCE_OPEN","part_id":"K01-P-004","datum":{"A":"functional axial locating/retention face; exact CAD face binding OPEN","B":"guide-bore derived axis","C":"N/A rotational symmetry"},"gps":{"OD_to_bore":{"family":"TOTAL_RUNOUT or equivalent ISO GPS relation to datum B","numeric":"OPEN"},"face_orientation":{"family":"PERPENDICULARITY or equivalent to datum B","numeric":"OPEN"},"guide_bore_form":{"family":"only if final guide envelope/process capability requires form control","numeric":"OPEN"}},"surfaces":{"guide_bore":{"class":"GUIDE/SLIDING","texture":"OPEN"},"seat_OD":{"class":"LOCATING/SLIP","texture":"OPEN"},"axial_face":{"class":"MATING/RETENTION","texture":"OPEN"}},"edges":{"guide_entry":"deburr/break edge; no scoring or PEEK shaving; numeric chamfer/radius OPEN","functional_surfaces":"no burrs, raised lips, torn polymer or scoring"},"inspection":{"reference_C":20,"conditioning":"OPEN pending production material qualification","methods":{"guide_bore":"small-bore metrology suitable for PEEK; final gage after numeric limit release","seat_OD":"low-force micrometer/comparator","OAL":"low-force comparator/height measurement","OD_to_bore":"functional runout fixture/CMM/optical method reproducing datum architecture","face_orientation":"CMM/comparator against datum-axis fixture","surface":"visual/optical now; quantitative roughness after texture release"},"rule":"gage uncertainty must be small relative to final tolerance"},"exemplars":{"root":ex.get('exemplar_root'),"class":ex.get('classification'),"authority":"NONE"},"open":{"guide_numeric":True,"seat_tolerance":True,"axial_tolerance":True,"GPS_numeric":True,"texture_numeric":True,"material_conditioning":True},"native_mutation":"NONE"}
 wr(repo/P['rep'],rep)
 wr(repo/P['edr'],{"schema":"k01.edr.v1","decision_id":"EDR-042","date":"2026-09-17","subject":"P004 datum/GPS/surface/edge/inspection architecture","status":"ACCEPTED_ARCHITECTURE__NUMERIC_VALUES_OPEN","decision":["A = functional axial locating/retention face; exact CAD binding OPEN","B = guide-bore derived axis","C = N/A","OD↔bore uses runout/equivalent GPS family; numeric OPEN","functional face uses perpendicularity/equivalent orientation to B; numeric OPEN","guide bore/seat OD/axial face surface classes defined; numeric texture OPEN","inspection methods defined; numeric acceptance OPEN",r"D:\Marvilon\K01\cad\drawings\exemplars is visual-quality reference only, NONFINAL/NONAUTHORITATIVE"],"not_accepted":["no numeric GTOL","no Ra/Rz","no size tolerance","no CAD/DimXpert/drawing mutation"]})
 pd=rd(repo/P['pd'],{}) or {};pd['datum_system']={'A':'functional axial face; exact CAD binding OPEN','B':'guide-bore axis','C':'N/A'};setc(pd,'P004-C04',{'name':'OD-to-bore relation','status':'OPEN','architecture':'runout/equivalent ISO GPS to B','numeric_tolerance':'OPEN','source':'EDR-042'});setc(pd,'P004-C05',{'name':'functional face orientation','status':'OPEN','architecture':'perpendicularity/equivalent to B','numeric_tolerance':'OPEN','source':'EDR-042'});setc(pd,'P004-C06',{'name':'guide bore texture','status':'OPEN','surface_class':'GUIDE/SLIDING','numeric_texture':'OPEN','source':'EDR-042'});setc(pd,'P004-C07',{'name':'seat OD texture','status':'OPEN','surface_class':'LOCATING/SLIP','numeric_texture':'OPEN','source':'EDR-042'});pd['status']='PARTIAL_PRODUCT_DEFINITION__MATERIAL_QUALIFICATION_AND_NUMERIC_LIMITS_OPEN';pd['product_definition_ready']=False;wr(repo/P['pd'],pd)
 wr(repo/P['insp'],{"schema":"k01.p004.inspection_plan.current.v1","generated_utc":now(),"part_id":"K01-P-004","status":"METHOD_ARCHITECTURE_DEFINED__NUMERIC_ACCEPTANCE_OPEN","reference_temperature_C":20,"conditioning":"OPEN_PRODUCTION_PEEK_CONDITIONING_PROCEDURE","methods":rep['inspection']['methods'],"exemplar_root":ex.get('exemplar_root'),"exemplar_role":"VISUAL_REFERENCE_ONLY"})
 read=rd(repo/P['read'],{}) or {};read.update({'generated_utc':now(),'status':'PARTIAL__DATUM_GPS_SURFACE_INSPECTION_ARCHITECTURE_DEFINED','product_definition_ready':False,'datum_state':'ARCHITECTURE_DEFINED__EXACT_FACE_BINDING_OPEN','gps_state':'CONTROL_FAMILIES_DEFINED__NUMERIC_OPEN','surface_state':'FUNCTIONAL_CLASSES_DEFINED__NUMERIC_OPEN','inspection_state':'METHOD_ARCHITECTURE_DEFINED__ACCEPTANCE_OPEN','next_blocker':'P004-MATERIAL-PRODUCTION-QUALIFICATION'});wr(repo/P['read'],read)
 f=rd(repo/P['front'],{}) or {};g=rd(repo/P['gate'],{}) or {};n=rd(repo/P['next'],{}) or {};b='P004-MATERIAL-PRODUCTION-QUALIFICATION';nid='K01-NA-P004-MATERIAL-PRODUCTION-QUALIFICATION';exp='PASS_P004_PRODUCTION_MATERIAL_EVIDENCE_CLASSIFIED__OPEN_RELEASE_GAPS_EXPLICIT';text='Control TECAPEEK PVX production material identity, applicable thermal/moisture properties, machining and dimensional-conditioning basis from manufacturer evidence. Preserve cold-range/property and supplier-lot gaps explicitly. No CAD/DimXpert/drawing mutation.';auth=[str(P['rep']).replace('\\','/'),str(P['edr']).replace('\\','/'),str(P['pd']).replace('\\','/'),str(P['insp']).replace('\\','/'),str(P['ex']).replace('\\','/')]
 n.update({'active_blocker':b,'current_blocker':b+':OPEN','next_1':text,'next_action_id':nid,'expected_closure':exp,'execution_mode':'MATERIAL_EVIDENCE_CLASSIFICATION__NO_NATIVE_MUTATION','authority_set':auth});wr(repo/P['next'],n);g.update({'generated_utc':now(),'intent':nid,'intent_text':text,'active_blocker':b,'expected_closure':exp,'mutation_authorized':False,'mutation_scope':'EVIDENCE/PD CONTROL ONLY; NO CAD; NO DIMXPERT; NO DRAWING','required_files':auth});wr(repo/P['gate'],g);f.update({'generated_utc':now(),'active_blocker':{'id':b,'state':'OPEN','timing':'ACTIVE_NOW'},'next_allowed_action':{'id':nid,'text':text,'authority_set':auth,'expected_closure':exp,'execution_mode':'MATERIAL_EVIDENCE_CLASSIFICATION__NO_NATIVE_MUTATION'}});f.setdefault('timing',{})['ACTIVE_NOW']=[b];wr(repo/P['front'],f)
 cm=rd(repo/P['center'],{}) or {};cm.update({'generated_utc':now(),'active_blocker':b,'next_action_id':nid,'drawing_exemplars':{'root':ex.get('exemplar_root'),'classification':ex.get('classification'),'authority':'NONE'}});wr(repo/P['center'],cm)
 subprocess.run([sys.executable,'tools/state/k01_lifecycle_state_reducer_v2.py','--repo-root',str(repo)],cwd=repo,check=True);subprocess.run([sys.executable,'tools/state/k01_temporal_coherence_guard_v1.py','--repo-root',str(repo),'--write-report'],cwd=repo,check=True);subprocess.run([sys.executable,'tools/state/k01_semantic_coherence_guard_v1.py','--repo-root',str(repo),'--write-report'],cwd=repo,check=True)
 print('PASS: EDR-042 P004 datum/GPS/surface/inspection architecture controlled.');print('NEXT: P004 material production evidence classification.');return 0
if __name__=='__main__':raise SystemExit(main())
