from __future__ import annotations
import argparse,datetime as dt,json,subprocess,sys
from pathlib import Path
R=Path(r"D:\BreshevEngineering\marvilon-k01")
P={"pd":Path("control/product_definition/K01-P-004_PRODUCT_DEFINITION_CURRENT.json"),"read":Path("reports/product_definition/K01-P-004_READINESS_CURRENT.json"),"tf":Path("reports/engineering/K01_P004_TECHNICAL_FILTER_CURRENT.json"),"insp":Path("reports/inspection/K01-P-004_INSPECTION_PLAN_CURRENT.json"),"therm":Path("reports/engineering/K01_P004_THERMAL_TOLERANCE_SCREEN_CURRENT.json"),"edr":Path("control/decisions/EDR-043_P004_TECAPEEK_PVX_PRODUCTION_MATERIAL_EVIDENCE.json"),"rep":Path("reports/engineering/K01_P004_TECAPEEK_PVX_MATERIAL_EVIDENCE_CURRENT.json"),"bom":Path("reports/control/K01_BOM_RELEASE_STATUS_CURRENT.json"),"next":Path("control/project/K01_NEXT_ACTIONS_CURRENT.json"),"gate":Path("control/project/K01_ACTIVE_STEP_GATE.json"),"front":Path("control/state/K01_COMPLETION_FRONTIER_CURRENT.json"),"center":Path("control/center/K01_CENTER_MASTER_FEED_CURRENT.json")}
def rd(p,d=None):
 try:return json.loads(p.read_text(encoding='utf-8-sig'))
 except:return d
def wr(p,o):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(o,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
def now():return dt.datetime.now(dt.timezone.utc).isoformat()
def guards(repo):
 for t in ('k01_temporal_coherence_guard_v1.py','k01_semantic_coherence_guard_v1.py'):
  if subprocess.run([sys.executable,'tools/state/'+t,'--repo-root',str(repo),'--write-report'],cwd=repo).returncode:raise SystemExit('HOLD: state guard failed')
def setc(pd,cid,u):
 xs=pd.setdefault('characteristics',[])
 for c in xs:
  if isinstance(c,dict) and c.get('id')==cid:c.update(u);return
 x={'id':cid};x.update(u);xs.append(x)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--repo-root',default=str(R));a=ap.parse_args();repo=Path(a.repo_root);guards(repo)
 for k in ('pd','read','insp','therm','next','gate','front'):
  if not (repo/P[k]).is_file():raise SystemExit('HOLD: missing '+str(P[k]))
 n=rd(repo/P['next'],{}) or {}
 if n.get('next_action_id')!='K01-NA-P004-MATERIAL-PRODUCTION-QUALIFICATION':raise SystemExit('HOLD: frontier not at P004 material qualification')
 ev={'manufacturer':'Ensinger','product':'TECAPEEK PVX black','class':'bearing/sliding grade modified PEEK','composition':'PEEK + 10% PTFE + 10% graphite + 10% carbon fibres','density_g_cm3':1.46,'Tg_C':146,'Tm_C':341,'service_short_C':300,'service_long_C':260,'CLTE_23_60_per_K':3e-5,'CLTE_23_100_per_K':3e-5,'thermal_conductivity_W_mK':0.82,'water_absorption_pct_24h_23C':0.02,'water_absorption_pct_96h_23C':0.03,'sources':['https://www.ensingerplastics.com/en/shapes/peek-tecapeek-pvx-black','https://www.ensingerplastics.com/en/thermoplastic-materials/peek-plastic/peek-machining']}
 rep={'schema':'k01.p004.material_evidence.current.v1','generated_utc':now(),'status':'PASS_DESIGN_MATERIAL_EVIDENCE__PRODUCTION_LOT_AND_COLD_RANGE_QUALIFICATION_OPEN','evidence':ev,'applicability':{'design_material_identity':'SUPPORTED','sliding_guide_use':'SUPPORTED','machined_part_route':'SUPPORTED','55C_upper_temperature':'SUPPORTED','water/humidity_material_family':'SUPPORTED','CLTE_23_to_55C':'SUPPORTED','CLTE_minus40_to_23C':'EXTRAPOLATED_SCREEN_ONLY','supplier_lot_stock_CoC':'OPEN','dimensional_conditioning_procedure':'OPEN'},'thermal_screen_correction':'30e-6/K is directly supported from 23...100 C. The existing -40...23 C extension is screening extrapolation, not manufacturer-validated cold-range property evidence.','release_boundary':{'design_material':'CONTROLLED','procurement_lot':'OPEN','stock_form/effectivity':'OPEN','cold_range_dimensional_property':'OPEN if -40 C acceptance required','conditioning':'OPEN','process_capability/FAI':'OPEN'}}
 wr(repo/P['rep'],rep);wr(repo/P['edr'],{'schema':'k01.edr.v1','decision_id':'EDR-043','date':'2026-09-17','subject':'P004 TECAPEEK PVX production material evidence boundary','status':'ACCEPTED_MATERIAL_EVIDENCE__PRODUCTION_QUALIFICATION_PARTIAL','decision':['Retain Ensinger TECAPEEK PVX black as P004 design material','Use manufacturer CLTE 30e-6/K as direct evidence from 23 C upward; below 23 C remains extrapolated screen unless qualified cold data is obtained','Manufacturer evidence supports bearing/sliding use, machining, low moisture absorption and 55 C service','Supplier lot/stock/CoC and dimensional conditioning remain production-release evidence','Do not claim -40 C production tolerance verification from current manufacturer CLTE data alone'],'sources':ev['sources'],'downstream_impact':{'P004':'design material evidence strengthened','thermal_screen':'PASS_SCREEN_WITH_LOW_T_EXTRAPOLATION_LIMITATION','BOM':'material identity controlled; lot/stock/effectivity OPEN','CAD':'NONE','DimXpert':'NONE','drawing':'NONE'}})
 pd=rd(repo/P['pd'],{}) or {};pd['material']={'designation':'TECAPEEK PVX black','manufacturer':'Ensinger','state':'RELEASED_DESIGN_MATERIAL__PRODUCTION_LOT_STOCK_CONDITIONING_OPEN','source':'EDR-043'};setc(pd,'P004-C08',{'name':'Material','value':'Ensinger TECAPEEK PVX black','status':'RELEASED','release_scope':'DESIGN_MATERIAL_IDENTITY_ONLY','open_evidence':'lot/stock CoC; conditioning; cold-range dimensional property if -40 C release required','source':'EDR-043'});pd['status']='PARTIAL_PRODUCT_DEFINITION__NUMERIC_TOLERANCE_AND_CONDITIONING_DEPENDENCIES_OPEN';pd['product_definition_ready']=False;wr(repo/P['pd'],pd)
 read=rd(repo/P['read'],{}) or {};read.update({'generated_utc':now(),'status':'PARTIAL__DESIGN_MATERIAL_EVIDENCE_CLOSED__PRODUCTION_QUALIFICATION_OPEN','product_definition_ready':False,'material_state':'DESIGN_MATERIAL_RELEASED__LOT_STOCK_CONDITIONING_OPEN','thermal_state':'23_TO_55_DIRECTLY_SUPPORTED__BELOW_23_TO_MINUS40_EXTRAPOLATED_SCREEN','next_blocker':'P004-OPEN-DEPENDENCY-CLOSURE-PLAN'});wr(repo/P['read'],read)
 insp=rd(repo/P['insp'],{}) or {};insp['generated_utc']=now();insp['conditioning']='OPEN — final dimensional conditioning/measurement procedure required for production acceptance';insp['material_evidence_authority']='EDR-043';wr(repo/P['insp'],insp)
 if (repo/P['bom']).is_file():
  b=rd(repo/P['bom'],{}) or {};b['generated_utc']=now();b['P004_update']={'material_design_identity':'Ensinger TECAPEEK PVX black','state':'DESIGN_MATERIAL_CONTROLLED__SUPPLIER_LOT_STOCK_EFFECTIVITY_OPEN','source':'EDR-043'};wr(repo/P['bom'],b)
 f=rd(repo/P['front'],{}) or {};g=rd(repo/P['gate'],{}) or {};n=rd(repo/P['next'],{}) or {};b='P004-OPEN-DEPENDENCY-CLOSURE-PLAN';nid='K01-NA-P004-OPEN-DEPENDENCY-CLOSURE';exp='PASS_P004_REMAINING_DEPENDENCIES_CLASSIFIED__EXECUTABLE_NEXT_SELECTED';text='Classify remaining P004 dependencies without inventing values: guide numeric envelope, seat/axial temperature applicability, low-temperature material evidence/requirement scope, exact datum-A CAD binding, and final numeric GPS/texture/tolerance allocation.';auth=[str(P['rep']).replace('\\','/'),str(P['edr']).replace('\\','/'),str(P['pd']).replace('\\','/'),str(P['read']).replace('\\','/'),str(P['insp']).replace('\\','/')]
 n.update({'active_blocker':b,'current_blocker':b+':OPEN','next_1':text,'next_action_id':nid,'expected_closure':exp,'execution_mode':'DEPENDENCY_CLASSIFICATION__NO_NATIVE_MUTATION','authority_set':auth});wr(repo/P['next'],n);g.update({'generated_utc':now(),'intent':nid,'intent_text':text,'active_blocker':b,'expected_closure':exp,'mutation_authorized':False,'mutation_scope':'DEPENDENCY/REQUIREMENT ANALYSIS ONLY; NO CAD; NO DIMXPERT; NO DRAWING','required_files':auth});wr(repo/P['gate'],g);f.update({'generated_utc':now(),'active_blocker':{'id':b,'state':'OPEN','timing':'ACTIVE_NOW'},'next_allowed_action':{'id':nid,'text':text,'authority_set':auth,'expected_closure':exp,'execution_mode':'DEPENDENCY_CLASSIFICATION__NO_NATIVE_MUTATION'}});f.setdefault('timing',{})['ACTIVE_NOW']=[b];wr(repo/P['front'],f)
 cm=rd(repo/P['center'],{}) or {};cm.update({'generated_utc':now(),'active_blocker':b,'next_action_id':nid,'p004_material':{'design_material':'Ensinger TECAPEEK PVX black','design_material_state':'RELEASED','production_lot_stock_conditioning':'OPEN','cold_range_property':'SCREEN_EXTRAPOLATION_ONLY'}});wr(repo/P['center'],cm)
 subprocess.run([sys.executable,'tools/state/k01_lifecycle_state_reducer_v2.py','--repo-root',str(repo)],cwd=repo,check=True);subprocess.run([sys.executable,'tools/state/k01_temporal_coherence_guard_v1.py','--repo-root',str(repo),'--write-report'],cwd=repo,check=True);subprocess.run([sys.executable,'tools/state/k01_semantic_coherence_guard_v1.py','--repo-root',str(repo),'--write-report'],cwd=repo,check=True)
 print('PASS: EDR-043 P004 material evidence classified.');print('DESIGN MATERIAL = RELEASED identity; lot/stock/conditioning OPEN; low-T CLTE SCREEN only.');print('NEXT: remaining P004 dependency closure plan.');return 0
if __name__=='__main__':raise SystemExit(main())
