using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Web.Script.Serialization;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;

public class K01D006BaseDrawingV7
{
    static string Arg(string[] a,string k){for(int i=0;i<a.Length-1;i++)if(a[i]==k)return a[i+1];return null;}
    static void Need(bool ok,string msg){if(!ok)throw new Exception(msg);}
    static bool Eq(string a,string b){return String.Equals(a??"",b??"",StringComparison.OrdinalIgnoreCase);}
    static IEnumerable Items(object o){if(o==null)yield break;Array a=o as Array;if(a!=null){foreach(object x in a)yield return x;yield break;}IEnumerable e=o as IEnumerable;if(e!=null)foreach(object x in e)yield return x;}
    static string Sha(string p){using(FileStream fs=new FileStream(p,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))using(SHA256 h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(fs)).Replace("-","").ToLowerInvariant();}
    static Dictionary<string,object> Json(string p){JavaScriptSerializer js=new JavaScriptSerializer();js.MaxJsonLength=Int32.MaxValue;return js.Deserialize<Dictionary<string,object>>(File.ReadAllText(p,Encoding.UTF8));}
    static Dictionary<string,object> Dict(object o){return o as Dictionary<string,object>;}
    static string Str(Dictionary<string,object> d,string k){object v;return d!=null&&d.TryGetValue(k,out v)&&v!=null?Convert.ToString(v,CultureInfo.InvariantCulture):"";}
    static double Num(Dictionary<string,object> d,string k,double fallback){object v;if(d!=null&&d.TryGetValue(k,out v)&&v!=null)try{return Convert.ToDouble(v,CultureInfo.InvariantCulture);}catch{}return fallback;}
    static object Obj(Dictionary<string,object> d,string k){object v;return d!=null&&d.TryGetValue(k,out v)?v:null;}
    static string One(string s){return (s??"").Replace("\r"," ").Replace("\n"," ").Replace("=","-");}

    static Dictionary<string,object> Characteristic(Dictionary<string,object> root,string id){foreach(object o in Items(Obj(root,"characteristics"))){Dictionary<string,object> c=Dict(o);if(c!=null&&Eq(Str(c,"id"),id))return c;}return null;}
    static List<string> BindingRefs(Dictionary<string,object> root,string id){var r=new List<string>();Dictionary<string,object> c=Characteristic(root,id),b=Dict(Obj(c,"solidworks_binding"));foreach(object o in Items(Obj(b,"entities"))){Dictionary<string,object> e=Dict(o);string s=Str(e,"persist_ref_b64");if(!String.IsNullOrWhiteSpace(s))r.Add(s);}return r;}
    static List<string> BlindRefs(Dictionary<string,object> root,string key){var r=new List<string>();Dictionary<string,object> b=Dict(Obj(root,"blind_end"));foreach(object o in Items(Obj(b,key))){Dictionary<string,object> e=Dict(o);string s=Str(e,"persist_ref_b64");if(!String.IsNullOrWhiteSpace(s))r.Add(s);}return r;}
    static object Resolve(ModelDoc2 part,string b64,out int state){state=-999;try{return part.Extension.GetObjectByPersistReference3(Convert.FromBase64String(b64),out state);}catch{return null;}}
    static Surface Surf(Face2 f){try{return f.IGetSurface();}catch{return null;}}
    static double[] DA(object o){List<double> x=new List<double>();foreach(object q in Items(o))try{x.Add(Convert.ToDouble(q,CultureInfo.InvariantCulture));}catch{}return x.ToArray();}
    static double PlaneX(Face2 f){Surface s=Surf(f);if(s==null||!s.IsPlane())return Double.NaN;double[] p=DA(s.PlaneParams);return p.Length>=6?p[3]:Double.NaN;}
    static double CylRadiusMm(Face2 f){Surface s=Surf(f);if(s==null||!s.IsCylinder())return Double.NaN;double[] p=DA(s.CylinderParams);return p.Length>=7?p[6]*1000.0:Double.NaN;}
    static List<Face2> ResolveFaces(ModelDoc2 part,List<string> refs,List<string> log,string tag){var r=new List<Face2>();for(int i=0;i<refs.Count;i++){int st;object o=Resolve(part,refs[i],out st);Face2 f=o as Face2;log.Add("RESOLVE "+tag+" idx="+i+" state="+st+" face="+(f!=null));if(f!=null)r.Add(f);}return r;}
    static Face2 FindCylinderByRadius(ModelDoc2 part,double mm){PartDoc pd=part as PartDoc;if(pd==null)return null;Face2 best=null;double err=1e9;foreach(object bo in Items(pd.GetBodies2((int)swBodyType_e.swSolidBody,true))){Body2 b=bo as Body2;if(b==null)continue;foreach(object fo in Items(b.GetFaces())){Face2 f=fo as Face2;if(f==null)continue;double r=CylRadiusMm(f);if(Double.IsNaN(r))continue;double e=Math.Abs(r-mm/2.0);if(e<err){err=e;best=f;}}}return err<=0.005?best:null;}
    static List<Face2> AllPlanes(ModelDoc2 part){var r=new List<Face2>();PartDoc pd=part as PartDoc;if(pd==null)return r;foreach(object bo in Items(pd.GetBodies2((int)swBodyType_e.swSolidBody,true))){Body2 b=bo as Body2;if(b==null)continue;foreach(object fo in Items(b.GetFaces())){Face2 f=fo as Face2;if(f!=null&&!Double.IsNaN(PlaneX(f)))r.Add(f);}}return r;}
    static bool PlanePairNear(List<Face2> ps,double expectedMm,bool preferHighX,out Face2 a,out Face2 b){a=null;b=null;double best=1e9,bestX=-1e9;for(int i=0;i<ps.Count;i++)for(int j=i+1;j<ps.Count;j++){double xi=PlaneX(ps[i]),xj=PlaneX(ps[j]);if(Double.IsNaN(xi)||Double.IsNaN(xj))continue;double dist=Math.Abs(xi-xj)*1000.0,err=Math.Abs(dist-expectedMm),mx=Math.Max(xi,xj);if(err<best-1e-6||(Math.Abs(err-best)<=1e-6&&preferHighX&&mx>bestX)){best=err;bestX=mx;a=ps[i];b=ps[j];}}return a!=null&&b!=null&&best<=0.02;}

    static string VName(View v){try{return v.GetName2()??"";}catch{return "";}}
    static string VRef(View v){try{return v.GetReferencedModelName()??"";}catch{return "";}}
    static List<View> Views(DrawingDoc dr,string partBase){var r=new List<View>();View v=dr.GetFirstView() as View;if(v!=null)v=v.GetNextView() as View;while(v!=null){string p=VRef(v);if(!String.IsNullOrWhiteSpace(p)&&Eq(Path.GetFileName(p),partBase))r.Add(v);v=v.GetNextView() as View;}return r;}
    static double[] Outline(View v){try{return DA(v.GetOutline());}catch{return new double[0];}}
    static bool IsIso(View v){string n=VName(v);return n.IndexOf("iso",StringComparison.OrdinalIgnoreCase)>=0;}
    static List<View> OrderViews(List<View> views,int preference){var r=new List<View>();if(preference==1){foreach(View v in views)if(VName(v).IndexOf("Section",StringComparison.OrdinalIgnoreCase)>=0)r.Add(v);}else if(preference==0){foreach(View v in views)if(Eq(VName(v),"Drawing View1"))r.Add(v);}foreach(View v in views)if(!r.Contains(v)&&!IsIso(v))r.Add(v);foreach(View v in views)if(!r.Contains(v))r.Add(v);return r;}
    static void PositionFor(View v,int slot,out double x,out double y){double[] o=Outline(v);if(o.Length>=4){x=Math.Min(0.405,o[2]+0.014);y=Math.Max(0.035,Math.Min(0.280,o[3]-0.012-0.012*(slot%5)));}else{x=0.390;y=0.250-0.012*(slot%5);}}
    static void PositionLinear(View v,int slot,out double x,out double y){double[] o=Outline(v);if(o.Length>=4){x=Math.Max(0.020,Math.Min(0.400,(o[0]+o[2])/2.0+0.012*((slot%3)-1)));y=Math.Max(0.040,Math.Min(0.282,o[3]+0.012+0.010*(slot/3)));}else{x=0.18+0.012*((slot%3)-1);y=0.260;}}
    static bool DeleteAnnotation(ModelDoc2 doc,Annotation a){try{if(a==null)return false;doc.ClearSelection2(true);bool sel=false;try{sel=a.Select3(false,null);}catch{}if(!sel)try{sel=a.Select2(false,0);}catch{}if(!sel)return false;bool ok=doc.Extension.DeleteSelection2((int)swDeleteSelectionOptions_e.swDelete_Absorbed);doc.ClearSelection2(true);return ok;}catch{doc.ClearSelection2(true);return false;}}
    static void DeleteDisplay(ModelDoc2 doc,DisplayDimension dd){try{DeleteAnnotation(doc,dd==null?null:dd.GetAnnotation() as Annotation);}catch{}doc.ClearSelection2(true);}
    static bool IsReference(DisplayDimension dd){try{Dimension d=dd==null?null:dd.GetDimension2(0);return d!=null&&d.IsReference();}catch{return false;}}
    static bool SelectInView(View v,object modelEntity,bool append){if(v==null||modelEntity==null)return false;try{Entity ce=v.GetCorrespondingEntity(modelEntity) as Entity;if(ce!=null&&ce.Select4(append,null))return true;}catch{}try{return v.SelectEntity(modelEntity,append);}catch{return false;}}
    static double UserMm(DisplayDimension dd,ModelDoc2 doc){try{Dimension d=dd.GetDimension2(0);return d==null?Double.NaN:d.IGetUserValueIn2(doc);}catch{return Double.NaN;}}
    static void NameDim(DisplayDimension dd,string name){try{Dimension d=dd.GetDimension2(0);if(d!=null)d.Name=name;}catch{}}
    static void TolNone(DisplayDimension dd){try{Dimension d=dd.GetDimension2(0);DimensionTolerance t=d==null?null:d.Tolerance as DimensionTolerance;if(t!=null)t.Type=(int)swTolType_e.swTolNONE;}catch{}}
    static bool TolH7(DisplayDimension dd){try{Dimension d=dd.GetDimension2(0);DimensionTolerance t=d==null?null:d.Tolerance as DimensionTolerance;if(t==null)return false;t.Type=(int)swTolType_e.swTolFIT;bool ok=t.SetFitValues("H7","");string h="";try{h=t.GetHoleFitValue()??"";}catch{}return ok&&Eq(h,"H7");}catch{return false;}}

    static bool TryDiameter(ModelDoc2 draw,List<View> views,Face2 face,double expectedMm,string id,bool h7,int preference,List<string> log,int slot,out string viewName){viewName="";if(face==null){log.Add("DIM "+id+" source_face=MISSING");return false;}var candidates=new List<object>();foreach(object eo in Items(face.GetEdges()))if(eo is Entity)candidates.Add(eo);candidates.Add(face);foreach(View v in OrderViews(views,preference)){foreach(object candidate in candidates){draw.ClearSelection2(true);if(!SelectInView(v,candidate,false))continue;double x,y;PositionFor(v,slot,out x,out y);DisplayDimension dd=null;try{dd=draw.AddDiameterDimension2(x,y,0) as DisplayDimension;}catch(Exception ex){log.Add("DIM "+id+" view="+VName(v)+" add_diam_err="+ex.GetType().Name);}if(dd==null){draw.ClearSelection2(true);continue;}double val=UserMm(dd,draw);bool nominal=Double.IsNaN(val)||Math.Abs(Math.Abs(val)-expectedMm)<=0.02;if(!nominal){log.Add("DIM "+id+" view="+VName(v)+" wrong_value="+val.ToString("G17",CultureInfo.InvariantCulture));DeleteDisplay(draw,dd);continue;}bool sem=h7?TolH7(dd):true;if(!h7)TolNone(dd);NameDim(dd,"K01_"+id);viewName=VName(v);log.Add("DIM "+id+" CREATED view="+viewName+" value_mm="+val.ToString("G17",CultureInfo.InvariantCulture)+" H7="+sem+" ref="+IsReference(dd));draw.ClearSelection2(true);return !h7||sem;}log.Add("DIM "+id+" view="+VName(v)+" no_valid_candidate");}return false;}
    static DisplayDimension AddLinearByMode(ModelDoc2 draw,double x,double y,int mode){try{if(mode==1)return draw.AddHorizontalDimension2(x,y,0) as DisplayDimension;if(mode==2)return draw.AddVerticalDimension2(x,y,0) as DisplayDimension;return draw.AddDimension2(x,y,0) as DisplayDimension;}catch{return null;}}
    static bool TryLinear(ModelDoc2 draw,List<View> views,Face2 a,Face2 b,double expectedMm,string id,List<string> log,int slot,out string viewName){viewName="";if(a==null||b==null){log.Add("DIM "+id+" source_face=MISSING");return false;}foreach(View v in OrderViews(views,1)){for(int mode=0;mode<3;mode++){draw.ClearSelection2(true);bool s1=SelectInView(v,a,false),s2=s1&&SelectInView(v,b,true);if(!(s1&&s2)){draw.ClearSelection2(true);break;}double x,y;PositionLinear(v,slot,out x,out y);DisplayDimension dd=AddLinearByMode(draw,x,y,mode);if(dd==null){log.Add("DIM "+id+" view="+VName(v)+" mode="+mode+" add_failed");continue;}double val=UserMm(dd,draw);bool nominal=Double.IsNaN(val)||Math.Abs(Math.Abs(val)-expectedMm)<=0.02;if(!nominal){log.Add("DIM "+id+" view="+VName(v)+" mode="+mode+" wrong_value="+val.ToString("G17",CultureInfo.InvariantCulture));DeleteDisplay(draw,dd);continue;}TolNone(dd);NameDim(dd,"K01_"+id);viewName=VName(v);log.Add("DIM "+id+" CREATED view="+viewName+" mode="+mode+" value_mm="+val.ToString("G17",CultureInfo.InvariantCulture)+" ref="+IsReference(dd));draw.ClearSelection2(true);return true;}}return false;}
    static void AddNote(ModelDoc2 doc,string text,double x,double y,List<string> log,string tag){try{doc.ClearSelection2(true);Note n=doc.InsertNote(text) as Note;if(n==null){log.Add("NOTE "+tag+" FAIL InsertNote");return;}Annotation a=n.GetAnnotation() as Annotation;if(a!=null){a.SetPosition(x,y,0);n.LockPosition=true;}log.Add("NOTE "+tag+" CREATED text="+One(text));}catch(Exception ex){log.Add("NOTE "+tag+" ERROR="+ex.GetType().Name+":"+One(ex.Message));}}
    static bool IsLegacyDebugNote(string t){t=t??"";return t.StartsWith("K01-D-006 | K01-P-007",StringComparison.OrdinalIgnoreCase)||t.StartsWith("DESIGN REVIEW CANDIDATE",StringComparison.OrdinalIgnoreCase)||t.StartsWith("MODEL-BASED DESIGN REVIEW CANDIDATE",StringComparison.OrdinalIgnoreCase)||t.IndexOf("CURRENT PROVEN NATIVE PMI",StringComparison.OrdinalIgnoreCase)>=0;}
    static void CleanupLegacySheet(ModelDoc2 doc,DrawingDoc dr,List<string> log){int tables=0,notes=0;View v=dr.GetFirstView() as View;while(v!=null){TableAnnotation ta=null;try{ta=v.GetFirstTableAnnotation() as TableAnnotation;}catch{}while(ta!=null){TableAnnotation next=null;try{next=ta.GetNext();}catch{}try{if(ta.Type==(int)swTableAnnotationType_e.swTableAnnotation_General){Annotation a=ta.GetAnnotation() as Annotation;if(DeleteAnnotation(doc,a))tables++;}}catch{}ta=next;}Note n=null;try{n=v.GetFirstNote() as Note;}catch{}while(n!=null){Note next=null;try{next=n.GetNext() as Note;}catch{}string text="";try{text=n.GetText()??"";}catch{}if(IsLegacyDebugNote(text)){try{if(DeleteAnnotation(doc,n.GetAnnotation() as Annotation))notes++;}catch{}}n=next;}v=v.GetNextView() as View;}log.Add("CLEANUP general_tables="+tables+" debug_notes="+notes);}
    static void SafeScale(View v,double s){try{v.UseSheetScale=0;v.UseParentScale=false;v.ScaleDecimal=s;}catch{}}
    static void ApplyViewScales(List<View> views,List<string> log){foreach(View v in views){string n=VName(v);double s=2.0;if(n.IndexOf("Section",StringComparison.OrdinalIgnoreCase)>=0||Eq(n,"Drawing View1"))s=5.0;SafeScale(v,s);log.Add("VIEW_SCALE "+n+"="+s.ToString("0.###",CultureInfo.InvariantCulture));}}
    static void MoveView(View v,double x,double y,List<string> log){try{v.PositionLocked=false;v.Position=new double[]{x,y};log.Add("VIEW_POS "+VName(v)+"="+x.ToString("0.000",CultureInfo.InvariantCulture)+","+y.ToString("0.000",CultureInfo.InvariantCulture));}catch(Exception ex){log.Add("VIEW_POS "+VName(v)+" ERROR="+ex.GetType().Name);}}
    static void ApplyBaseLayout(List<View> views,List<string> log){foreach(View v in views){string n=VName(v);if(Eq(n,"Drawing View1"))MoveView(v,0.090,0.200,log);else if(n.IndexOf("Section",StringComparison.OrdinalIgnoreCase)>=0)MoveView(v,0.285,0.200,log);else if(Eq(n,"Drawing View2"))MoveView(v,0.135,0.082,log);else if(Eq(n,"Drawing View3"))MoveView(v,0.300,0.090,log);}}

    static Face2 FirstCylinder(List<Face2> fs){foreach(Face2 f in fs)if(!Double.IsNaN(CylRadiusMm(f)))return f;return null;}
    static List<Face2> Planes(List<Face2> fs){var r=new List<Face2>();foreach(Face2 f in fs)if(!Double.IsNaN(PlaneX(f)))r.Add(f);return r;}
    static bool ExtremePlanes(List<Face2> ps,out Face2 a,out Face2 b){a=null;b=null;if(ps.Count<2)return false;double mn=1e9,mx=-1e9;foreach(Face2 f in ps){double x=PlaneX(f);if(Double.IsNaN(x))continue;if(x<mn){mn=x;a=f;}if(x>mx){mx=x;b=f;}}return a!=null&&b!=null&&Math.Abs(mx-mn)>1e-8;}

    static string FindP007Reference(SldWorks sw,string drawing,List<string> log){object deps=null;try{deps=sw.GetDocumentDependencies2(drawing,true,true,false);}catch{}string prev="";foreach(object q in Items(deps)){string s=Convert.ToString(q)??"";if(File.Exists(s)&&s.EndsWith(".SLDPRT",StringComparison.OrdinalIgnoreCase)&&Path.GetFileName(s).IndexOf("K01-P-007",StringComparison.OrdinalIgnoreCase)>=0)return s;prev=s;}return "";}
    static bool SaveAs(ModelDoc2 doc,string p){int e=0,w=0;bool ok=doc.Extension.SaveAs(p,(int)swSaveAsVersion_e.swSaveAsCurrentVersion,(int)swSaveAsOptions_e.swSaveAsOptions_Silent,null,ref e,ref w);return ok&&e==0;}

    public static int Main(string[] args){
        string drawing=Arg(args,"--drawing"),partPath=Arg(args,"--part"),charsPath=Arg(args,"--characteristics"),profilePath=Arg(args,"--profile"),outRoot=Arg(args,"--out-root"),report=Arg(args,"--report");
        if(String.IsNullOrWhiteSpace(drawing)||String.IsNullOrWhiteSpace(partPath)||String.IsNullOrWhiteSpace(charsPath)||String.IsNullOrWhiteSpace(profilePath)||String.IsNullOrWhiteSpace(outRoot)||String.IsNullOrWhiteSpace(report)){Console.Error.WriteLine("missing args");return 2;}
        SldWorks sw=null;ModelDoc2 part=null,doc=null;bool created=false,inputPrefCaptured=false,oldInput=false;List<string> log=new List<string>();
        try{
            Need(File.Exists(drawing),"source drawing missing");Need(File.Exists(partPath),"drawing-source part missing");Need(File.Exists(charsPath),"characteristics missing");Need(File.Exists(profilePath),"profile missing");
            string sourceDrawingSha=Sha(drawing),sourcePartSha=Sha(partPath);Dictionary<string,object> chars=Json(charsPath),profile=Json(profilePath);
            Type t=Type.GetTypeFromProgID("SldWorks.Application");Need(t!=null,"SOLIDWORKS ProgID unavailable");sw=(SldWorks)Activator.CreateInstance(t);created=true;sw.Visible=true;Need(typeof(SldWorks).Assembly.GetName().Version.Major==26,"SOLIDWORKS interop major is not 26");
            int pe=0,pw=0;part=sw.OpenDoc6(partPath,(int)swDocumentTypes_e.swDocPART,(int)swOpenDocOptions_e.swOpenDocOptions_Silent,"",ref pe,ref pw) as ModelDoc2;Need(part!=null,"open part failed e="+pe+" w="+pw);
            string stamp=DateTime.Now.ToString("yyyyMMdd_HHmmss"),dir=Path.Combine(outRoot,"base_v7_"+stamp);Directory.CreateDirectory(dir);string dst=Path.Combine(dir,"K01-D-006_Hermetic_Magnetic_Can_BASE_V7_CANDIDATE.SLDDRW");File.Copy(drawing,dst,true);
            string oldRef=FindP007Reference(sw,dst,log);Need(!String.IsNullOrWhiteSpace(oldRef),"cannot resolve P007 reference in drawing copy");bool repl=sw.ReplaceReferencedDocument(dst,oldRef,partPath);log.Add("RELINK old="+oldRef+" new="+partPath+" return="+repl);Need(repl,"ReplaceReferencedDocument failed");
            int de=0,dw=0;doc=sw.OpenDoc6(dst,(int)swDocumentTypes_e.swDocDRAWING,(int)swOpenDocOptions_e.swOpenDocOptions_Silent,"",ref de,ref dw) as ModelDoc2;Need(doc!=null,"open drawing copy failed e="+de+" w="+dw);DrawingDoc dr=doc as DrawingDoc;Need(dr!=null,"not drawing");int ae=0;try{sw.ActivateDoc3(doc.GetTitle(),false,(int)swRebuildOnActivation_e.swDontRebuildActiveDoc,ref ae);}catch{}try{oldInput=sw.GetUserPreferenceToggle((int)swUserPreferenceToggle_e.swInputDimValOnCreate);inputPrefCaptured=true;sw.SetUserPreferenceToggle((int)swUserPreferenceToggle_e.swInputDimValOnCreate,false);}catch{}List<View> views=Views(dr,Path.GetFileName(partPath));Need(views.Count>=2,"fewer than two P007 drawing views after relink");CleanupLegacySheet(doc,dr,log);ApplyViewScales(views,log);ApplyBaseLayout(views,log);doc.EditRebuild3();

            // Current controlled authoring profile. Legacy candidate +/- values in older files are deliberately ignored here.
            double c02=14.10,c04=2.90,c05=33.00,c06=35.00,c07=10.00,c08=9.40,flangeT=3.00,blindT=1.00;
            Dictionary<string,object> pc=Dict(Obj(profile,"characteristics"));if(pc!=null){c02=Num(Dict(Obj(pc,"C02")),"diameter_mm",c02);c04=Num(Dict(Obj(pc,"C04")),"hole_diameter_mm",c04);c05=Num(Dict(Obj(pc,"C05")),"flange_od_mm",c05);flangeT=Num(Dict(Obj(pc,"C05")),"flange_thickness_mm",flangeT);c06=Num(Dict(Obj(pc,"C06")),"overall_length_mm",c06);c07=Num(Dict(Obj(pc,"C07")),"thin_can_od_mm",c07);c08=Num(Dict(Obj(pc,"C08")),"thin_can_id_mm",c08);blindT=Num(Dict(Obj(pc,"BLIND_END")),"thickness_mm_nominal",blindT);}

            List<Face2> f02=ResolveFaces(part,BindingRefs(chars,"C02"),log,"C02"),f04=ResolveFaces(part,BindingRefs(chars,"C04"),log,"C04"),f05=ResolveFaces(part,BindingRefs(chars,"C05"),log,"C05"),f06=ResolveFaces(part,BindingRefs(chars,"C06"),log,"C06");
            if(FirstCylinder(f02)==null){Face2 f=FindCylinderByRadius(part,c02);if(f!=null){f02.Add(f);log.Add("FALLBACK C02 cylinder_by_radius=True");}}
            if(FirstCylinder(f04)==null){Face2 f=FindCylinderByRadius(part,c04);if(f!=null){f04.Add(f);log.Add("FALLBACK C04 cylinder_by_radius=True");}}
            if(FirstCylinder(f05)==null){Face2 f=FindCylinderByRadius(part,c05);if(f!=null){f05.Add(f);log.Add("FALLBACK C05 cylinder_by_radius=True");}}
            Face2 c07f=FindCylinderByRadius(part,c07),c08f=FindCylinderByRadius(part,c08);log.Add("SCAN C07 radius="+c07+" found="+(c07f!=null));log.Add("SCAN C08 radius="+c08+" found="+(c08f!=null));
            List<Face2> bo=ResolveFaces(part,BlindRefs(chars,"outer_entities"),log,"BLIND_OUTER"),bi=ResolveFaces(part,BlindRefs(chars,"inner_entities"),log,"BLIND_INNER");

            bool d02=false,d04=false,d05=false,d06=false,d07=false,d08=false,dFT=false,dBT=false;string vn;
            d02=TryDiameter(doc,views,FirstCylinder(f02),c02,"C02_DIA14P10_H7",true,0,log,0,out vn);
            d05=TryDiameter(doc,views,FirstCylinder(f05),c05,"C05_FLANGE_OD33_NOM",false,0,log,1,out vn);
            d04=TryDiameter(doc,views,FirstCylinder(f04),c04,"C04_HOLE_DIA2P90_NOM",false,0,log,2,out vn);
            d07=TryDiameter(doc,views,c07f,c07,"C07_CAN_OD10_NOM",false,1,log,3,out vn);
            d08=TryDiameter(doc,views,c08f,c08,"C08_CAN_ID9P40_NOM",false,1,log,4,out vn);

            Face2 a,b;List<Face2> allp=AllPlanes(part),p05=Planes(f05);if(!ExtremePlanes(p05,out a,out b))PlanePairNear(allp,flangeT,false,out a,out b);if(a!=null&&b!=null)dFT=TryLinear(doc,views,a,b,flangeT,"C05_FLANGE_T3_NOM",log,0,out vn);
            List<Face2> p06=Planes(f06);if(!ExtremePlanes(p06,out a,out b))PlanePairNear(allp,c06,false,out a,out b);if(a!=null&&b!=null)d06=TryLinear(doc,views,a,b,c06,"C06_OAL35_NOM",log,1,out vn);
            if(!(bo.Count>0&&bi.Count>0)){if(PlanePairNear(allp,blindT,true,out a,out b)){bo.Clear();bi.Clear();bo.Add(a);bi.Add(b);log.Add("FALLBACK BLIND_END plane_pair=True");}}if(bo.Count>0&&bi.Count>0)dBT=TryLinear(doc,views,bo[0],bi[0],blindT,"BLIND_END_T1_NOM",log,2,out vn);

            // One compact controlled callout for the 3-hole pattern; positional tolerance stays explicitly OPEN.
            View end=null;foreach(View v in views)if(Eq(VName(v),"Drawing View1")){end=v;break;}if(end==null)end=views[0];double[] eo=Outline(end);double nx=eo.Length>=4?eo[0]:0.015,ny=eo.Length>=4?eo[1]-0.018:0.080;AddNote(doc,"3X Ø2.90 THRU  |  PCD Ø26.50 NOM  |  POSITION TOLERANCE OPEN",nx,Math.Max(0.075,ny),log,"C04_PATTERN");
            AddNote(doc,"C02 BORE DEPTH 2.00 NOM — DEPTH TOLERANCE OPEN  |  C08 RADIAL WALL 0.30 NOM",nx,Math.Max(0.060,ny-0.012),log,"C02_DEPTH_C08_WALL");
            AddNote(doc,"MATERIAL: AISI 316L / EN 1.4404",nx,Math.Max(0.045,ny-0.024),log,"C09_MATERIAL");
            AddNote(doc,"OPEN: C05/C06/C07/C08/BLIND-END RELEASE TOLERANCES; C10/C11/C12",nx,Math.Max(0.030,ny-0.036),log,"OPEN_BOUNDARY");

            doc.ForceRebuild3(false);int count=(d02?1:0)+(d04?1:0)+(d05?1:0)+(d06?1:0)+(d07?1:0)+(d08?1:0)+(dFT?1:0)+(dBT?1:0);bool critical=d02&&d05;string status=critical&&count>=6?"PASS_D006_BASE_DRAWING_V7":(count>=3?"PARTIAL_D006_BASE_DRAWING_V7":"HOLD_D006_BASE_DRAWING_V7");
            bool saved=SaveAs(doc,dst);Need(saved,"save base candidate failed");string pdf=Path.ChangeExtension(dst,"PDF"),bmp=Path.ChangeExtension(dst,"BMP");bool pdfOk=SaveAs(doc,pdf);doc.ViewZoomtofit2();bool bmpOk=doc.SaveBMP(bmp,1800,1273);string title=doc.GetTitle();sw.CloseDoc(title);doc=null;sw.CloseDoc(part.GetTitle());part=null;
            Need(Sha(drawing)==sourceDrawingSha,"source drawing changed");Need(Sha(partPath)==sourcePartSha,"drawing-source part changed");
            StringBuilder sb=new StringBuilder();sb.AppendLine("STATUS="+status);sb.AppendLine("SOURCE_DRAWING="+drawing);sb.AppendLine("SOURCE_DRAWING_SHA256="+sourceDrawingSha);sb.AppendLine("DRAWING_SOURCE_PART="+partPath);sb.AppendLine("DRAWING_SOURCE_PART_SHA256="+sourcePartSha);sb.AppendLine("OUTPUT_DRAWING="+dst);sb.AppendLine("OUTPUT_PDF="+pdf);sb.AppendLine("OUTPUT_BMP="+bmp);sb.AppendLine("PDF_OK="+pdfOk);sb.AppendLine("BMP_OK="+bmpOk);sb.AppendLine("P007_VIEW_COUNT="+views.Count);sb.AppendLine("CREATED_COUNT="+count);sb.AppendLine("C02_CREATED="+d02);sb.AppendLine("C04_HOLE_CREATED="+d04);sb.AppendLine("C05_CREATED="+d05);sb.AppendLine("C05_FLANGE_T_CREATED="+dFT);sb.AppendLine("C06_CREATED="+d06);sb.AppendLine("C07_CREATED="+d07);sb.AppendLine("C08_CREATED="+d08);sb.AppendLine("BLIND_END_CREATED="+dBT);sb.AppendLine("SOURCE_DRAWING_INVARIANT=True");sb.AppendLine("DRAWING_SOURCE_PART_INVARIANT=True");for(int i=0;i<log.Count;i++)sb.AppendLine("LOG_"+(i+1)+"="+One(log[i]));File.WriteAllText(report,sb.ToString(),Encoding.UTF8);
            Console.WriteLine("STATUS: "+status);Console.WriteLine("CREATED: "+count+" / 8");Console.WriteLine("C02 H7: "+d02+"  C05 Ø33: "+d05+"  C06 35: "+d06+"  C07 Ø10: "+d07+"  C08 Ø9.40: "+d08);Console.WriteLine("C04 Ø2.90: "+d04+"  FLANGE T3: "+dFT+"  BLIND T1: "+dBT);Console.WriteLine("DRAWING: "+dst);Console.WriteLine("PDF: "+pdf);Console.WriteLine("BMP: "+bmp);Console.WriteLine("REPORT: "+report);return status.StartsWith("HOLD_")?3:0;
        }catch(Exception ex){try{File.WriteAllText(report,"STATUS=HOLD_D006_BASE_DRAWING_V7_ERROR\nERROR="+ex.ToString()+"\n",Encoding.UTF8);}catch{}Console.Error.WriteLine(ex.ToString());return 2;}
        finally{try{if(doc!=null&&sw!=null)sw.CloseDoc(doc.GetTitle());}catch{}try{if(part!=null&&sw!=null)sw.CloseDoc(part.GetTitle());}catch{}try{if(inputPrefCaptured&&sw!=null)sw.SetUserPreferenceToggle((int)swUserPreferenceToggle_e.swInputDimValOnCreate,oldInput);}catch{}try{if(created&&sw!=null)sw.ExitApp();}catch{}}
    }
}
