using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;

public class K01D004IsoExemplarV1
{
    static string Arg(string[] a,string k){for(int i=0;i<a.Length-1;i++)if(a[i]==k)return a[i+1];return null;}
    static void Need(bool ok,string msg){if(!ok)throw new Exception(msg);}
    static bool Eq(string a,string b){return String.Equals(a??"",b??"",StringComparison.OrdinalIgnoreCase);}
    static IEnumerable Items(object o){if(o==null)yield break;Array a=o as Array;if(a!=null){foreach(object x in a)yield return x;yield break;}IEnumerable e=o as IEnumerable;if(e!=null)foreach(object x in e)yield return x;}
    static string One(string s){return (s??"").Replace("\r"," ").Replace("\n"," ").Replace("=","-");}
    static string F(double x,string fmt){return x.ToString(fmt,CultureInfo.InvariantCulture);}
    static string Sha(string p){using(FileStream fs=new FileStream(p,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))using(SHA256 h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(fs)).Replace("-","").ToLowerInvariant();}
    static double[] DA(object o){var z=new List<double>();foreach(object q in Items(o))try{z.Add(Convert.ToDouble(q,CultureInfo.InvariantCulture));}catch{}return z.ToArray();}
    static string VName(View v){try{return v.GetName2()??"";}catch{return "";}}
    static bool SaveAs(ModelDoc2 doc,string p){int e=0,w=0;bool ok=doc.Extension.SaveAs(p,(int)swSaveAsVersion_e.swSaveAsCurrentVersion,(int)swSaveAsOptions_e.swSaveAsOptions_Silent,null,ref e,ref w);if(!ok||e!=0)throw new Exception("SaveAs failed "+p+" e="+e+" w="+w);return true;}
    static bool SetSheetScale(DrawingDoc dr,double num,double den,List<string> log){try{Sheet sh=dr.GetCurrentSheet() as Sheet;Need(sh!=null,"current sheet missing");bool ok=sh.SetScale(num,den,false,false);log.Add("SHEET_SCALE "+F(num,"0.###")+":"+F(den,"0.###")+" ok="+ok);return ok;}catch(Exception ex){log.Add("SHEET_SCALE FAIL="+One(ex.Message));return false;}}
    static bool SheetFirstAngle(DrawingDoc dr){try{Sheet sh=dr.GetCurrentSheet() as Sheet;double[] p=sh==null?new double[0]:DA(sh.GetProperties2());return p.Length>=5&&Math.Abs(p[4])>0.5;}catch{return false;}}
    static void SetView(View v,double x,double y,double scale){try{v.PositionLocked=false;}catch{}try{v.UseSheetScale=0;}catch{}try{v.UseParentScale=false;}catch{}try{v.ScaleDecimal=scale;}catch{}try{v.Position=new double[]{x,y};}catch{}}

    static Surface Surf(Face2 f){try{return f.IGetSurface();}catch{return null;}}
    static double PlaneX(Face2 f){Surface s=Surf(f);if(s==null||!s.IsPlane())return Double.NaN;double[] p=DA(s.PlaneParams);return p.Length>=6?p[3]:Double.NaN;}
    static double CylRadiusMm(Face2 f){Surface s=Surf(f);if(s==null||!s.IsCylinder())return Double.NaN;double[] p=DA(s.CylinderParams);return p.Length>=7?p[6]*1000.0:Double.NaN;}
    static double Area(Face2 f){try{return f.GetArea();}catch{return 0;}}
    static List<Face2> Faces(ModelDoc2 part){var r=new List<Face2>();PartDoc pd=part as PartDoc;if(pd==null)return r;foreach(object bo in Items(pd.GetBodies2((int)swBodyType_e.swSolidBody,true))){Body2 b=bo as Body2;if(b==null)continue;foreach(object fo in Items(b.GetFaces())){Face2 f=fo as Face2;if(f!=null)r.Add(f);}}return r;}
    static Face2 UniqueCylinder(List<Face2> fs,double dia,string role,List<string> log){var q=new List<Face2>();foreach(Face2 f in fs){double r=CylRadiusMm(f);if(!Double.IsNaN(r)&&Math.Abs(2*r-dia)<=0.02)q.Add(f);}log.Add("BIND "+role+" dia="+F(dia,"0.###")+" matches="+q.Count);Need(q.Count==1,role+" ambiguous/missing cylinder: "+q.Count);return q[0];}
    static Face2 ExtremePlane(List<Face2> fs,bool min,string role,List<string> log){var q=new List<Face2>();double target=min?Double.PositiveInfinity:Double.NegativeInfinity;foreach(Face2 f in fs){double x=PlaneX(f);if(Double.IsNaN(x))continue;if(min){if(x<target)target=x;}else{if(x>target)target=x;}}Need(!Double.IsInfinity(target),role+" no planar faces");foreach(Face2 f in fs){double x=PlaneX(f);if(!Double.IsNaN(x)&&Math.Abs(x-target)<=0.000005)q.Add(f);}q.Sort(delegate(Face2 a,Face2 b){return Area(b).CompareTo(Area(a));});Need(q.Count>0,role+" missing extreme plane");log.Add("BIND "+role+" x_mm="+F(target*1000.0,"0.###")+" coplanar="+q.Count);return q[0];}

    static bool SelectInView(View v,object modelEntity,bool append){if(v==null||modelEntity==null)return false;try{Entity ce=v.GetCorrespondingEntity(modelEntity) as Entity;if(ce!=null&&ce.Select4(append,null))return true;}catch{}try{return v.SelectEntity(modelEntity,append);}catch{return false;}}
    static double UserMm(DisplayDimension dd,ModelDoc2 doc){try{Dimension d=dd.GetDimension2(0);return d==null?Double.NaN:d.IGetUserValueIn2(doc);}catch{return Double.NaN;}}
    static void FormatDim(DisplayDimension dd,int precision){if(dd==null)return;try{dd.ShowParenthesis=false;}catch{}try{dd.ShowLowerParenthesis=false;}catch{}try{dd.SetPrecision2(precision,precision,precision,precision);}catch{}}
    static void NameDim(DisplayDimension dd,string name){try{Dimension d=dd.GetDimension2(0);if(d!=null)d.Name=name;}catch{}try{Annotation a=dd.GetAnnotation() as Annotation;if(a!=null)a.SetName("K01D004_"+name);}catch{}}
    static DisplayDimension AcceptDim(ModelDoc2 doc,DisplayDimension dd,double expected,string id,int precision,List<string> log){if(dd==null)return null;double mm=UserMm(dd,doc);if(!Double.IsNaN(mm)&&Math.Abs(Math.Abs(mm)-expected)>0.03){try{Annotation a=dd.GetAnnotation() as Annotation;if(a!=null)a.Visible=(int)swAnnotationVisibilityState_e.swAnnotationHidden;}catch{}log.Add("DIM "+id+" REJECT actual="+F(mm,"0.######")+" expected="+F(expected,"0.######"));return null;}NameDim(dd,id);FormatDim(dd,precision);log.Add("DIM "+id+" OK actual="+(Double.IsNaN(mm)?"NaN":F(mm,"0.######")));doc.ClearSelection2(true);return dd;}
    static DisplayDimension Diameter(ModelDoc2 doc,View v,Face2 f,double expected,double x,double y,string id,int precision,string suffix,List<string> log){var cand=new List<object>();foreach(object eo in Items(f.GetEdges()))if(eo is Entity)cand.Add(eo);cand.Add(f);foreach(object q in cand){doc.ClearSelection2(true);if(!SelectInView(v,q,false))continue;DisplayDimension dd=null;try{dd=doc.AddDiameterDimension2(x,y,0) as DisplayDimension;}catch{}dd=AcceptDim(doc,dd,expected,id,precision,log);if(dd!=null){if(!String.IsNullOrWhiteSpace(suffix))try{dd.SetText((int)swDimensionTextParts_e.swDimensionTextSuffix,suffix);}catch{}return dd;}}log.Add("DIM "+id+" FAIL");return null;}
    static DisplayDimension Linear(ModelDoc2 doc,View v,Face2 a,Face2 b,double expected,double x,double y,string id,int precision,List<string> log){for(int mode=0;mode<2;mode++){doc.ClearSelection2(true);if(!SelectInView(v,a,false)||!SelectInView(v,b,true))continue;DisplayDimension dd=null;try{dd=mode==0?doc.AddHorizontalDimension2(x,y,0) as DisplayDimension:doc.AddDimension2(x,y,0) as DisplayDimension;}catch{}dd=AcceptDim(doc,dd,expected,id,precision,log);if(dd!=null)return dd;}log.Add("DIM "+id+" FAIL");return null;}

    static Note AddNote(ModelDoc2 doc,string text,double x,double y,string id,List<string> log){try{doc.ClearSelection2(true);Note n=doc.InsertNote(text) as Note;if(n==null){log.Add("NOTE "+id+" FAIL");return null;}Annotation a=n.GetAnnotation() as Annotation;if(a!=null){a.SetPosition(x,y,0);try{a.SetName("K01D004_"+id);}catch{}}try{n.SetName("K01D004_"+id);}catch{}try{n.LockPosition=true;}catch{}log.Add("NOTE "+id+" OK");return n;}catch(Exception ex){log.Add("NOTE "+id+" FAIL="+One(ex.Message));return null;}}
    static void SetProp(ModelDoc2 doc,string k,string v){CustomPropertyManager c=doc.Extension.get_CustomPropertyManager("");try{c.Delete2(k);}catch{}int r=c.Add(k,"Text",v??"");if(r==0)try{c.Set2(k,v??"");}catch{}}
    static void HideSheetNoteContaining(DrawingDoc dr,string token,List<string> log){int n=0;View v=dr.GetFirstView() as View;while(v!=null){Note note=null;try{note=v.GetFirstNote() as Note;}catch{}while(note!=null){Note next=null;try{next=note.GetNext() as Note;}catch{}string txt="";try{txt=note.GetText()??"";}catch{}if(txt.IndexOf(token,StringComparison.OrdinalIgnoreCase)>=0){try{Annotation a=note.GetAnnotation() as Annotation;if(a!=null){a.Visible=(int)swAnnotationVisibilityState_e.swAnnotationHidden;n++;}}catch{}}note=next;}v=v.GetNextView() as View;}log.Add("HIDE_TEMPLATE token="+token+" count="+n);}

    public static int Main(string[] args)
    {
        string partPath=Arg(args,"--part"),outRoot=Arg(args,"--out-root"),report=Arg(args,"--report");
        SldWorks sw=null;ModelDoc2 part=null,doc=null;bool created=false;var log=new List<string>();
        try
        {
            Need(File.Exists(partPath),"part missing: "+partPath);Need(!String.IsNullOrWhiteSpace(outRoot),"out-root missing");Need(!String.IsNullOrWhiteSpace(report),"report missing");
            string psha=Sha(partPath);string stamp=DateTime.Now.ToString("yyyyMMdd_HHmmss",CultureInfo.InvariantCulture);string cand=Path.Combine(outRoot,"d004_iso_exemplar_v1_"+stamp);string manual=Path.Combine(cand,"manual_finish"),generated=Path.Combine(cand,"generated"),evidence=Path.Combine(cand,"evidence");Directory.CreateDirectory(manual);Directory.CreateDirectory(generated);Directory.CreateDirectory(evidence);string dwg=Path.Combine(manual,"K01-D-004_ISO_FINISH.SLDDRW"),pdf=Path.Combine(manual,"K01-D-004_ISO_FINISH.PDF"),bmp=Path.Combine(manual,"K01-D-004_ISO_FINISH.BMP");
            Type t=Type.GetTypeFromProgID("SldWorks.Application");Need(t!=null,"SOLIDWORKS ProgID missing");sw=Activator.CreateInstance(t) as SldWorks;Need(sw!=null,"SOLIDWORKS activation failed");created=true;sw.Visible=true;Need(typeof(SldWorks).Assembly.GetName().Version.Major==26,"requires SOLIDWORKS 2018 interop major 26");
            int pe=0,pw=0;part=sw.OpenDoc6(partPath,(int)swDocumentTypes_e.swDocPART,(int)swOpenDocOptions_e.swOpenDocOptions_Silent,"",ref pe,ref pw) as ModelDoc2;Need(part!=null,"open source part failed e="+pe+" w="+pw);List<Face2> fs=Faces(part);Need(fs.Count>=4,"unexpected P004 topology face count="+fs.Count);Face2 idf=UniqueCylinder(fs,5.055,"GUIDE_ID",log);Face2 odf=UniqueCylinder(fs,6.54,"SEAT_OD",log);Face2 fmin=ExtremePlane(fs,true,"FACE_MIN",log);Face2 fmax=ExtremePlane(fs,false,"FACE_MAX",log);
            string templ=sw.GetUserPreferenceStringValue((int)swUserPreferenceStringValue_e.swDefaultTemplateDrawing);Need(!String.IsNullOrWhiteSpace(templ)&&File.Exists(templ),"default drawing template missing");doc=sw.NewDocument(templ,0,0,0) as ModelDoc2;Need(doc!=null,"new drawing failed");DrawingDoc dr=doc as DrawingDoc;Need(dr!=null,"new document is not drawing");bool setup=dr.SetupSheet5("Sheet1",(int)swDwgPaperSizes_e.swDwgPaperA3size,(int)swDwgTemplates_e.swDwgTemplateA3size,10,1,true,"",0.420,0.297,"",false);Need(setup,"SetupSheet5 failed");Need(SetSheetScale(dr,10,1,log),"sheet scale failed");Need(SheetFirstAngle(dr),"first-angle sheet property not active");
            View side=dr.CreateDrawViewFromModelView3(partPath,"*Front",0.125,0.177,0) as View;Need(side!=null,"LONG view creation failed");SetView(side,0.125,0.177,10.0);try{side.SetName2("K01D004_VIEW_LONG");}catch{}View endv=dr.CreateDrawViewFromModelView3(partPath,"*Right",0.285,0.177,0) as View;Need(endv!=null,"END view creation failed");SetView(endv,0.285,0.177,10.0);try{endv.SetName2("K01D004_VIEW_END");}catch{}doc.EditRebuild3();
            SetProp(doc,"DrawingNo","K01-D-004");SetProp(doc,"PartNo","K01-P-004");SetProp(doc,"Title","Front Guide Bushing");SetProp(doc,"Material","TECAPEEK PVX black (Ensinger)");SetProp(doc,"Status","ENGINEERING REVIEW");SetProp(doc,"Units","mm");SetProp(doc,"Projection","FIRST_ANGLE");SetProp(doc,"Scale","10:1");SetProp(doc,"Revision","");SetProp(doc,"DrawingSystem","K01_D004_ISO_EXEMPLAR_V1");SetProp(doc,"SourceModelSHA256",psha);SetProp(doc,"ReleaseState","HOLD");
            DisplayDimension dl=Linear(doc,side,fmin,fmax,8.0,0.125,0.238,"C03_OAL",2,log);DisplayDimension did=Diameter(doc,endv,idf,5.055,0.238,0.128,"C01_GUIDE_ID",3," THRU",log);DisplayDimension dod=Diameter(doc,endv,odf,6.54,0.344,0.222,"C02_SEAT_OD",2,"",log);
            int notes=0;if(AddNote(doc,"MATERIAL: TECAPEEK PVX black (Ensinger) - PRODUCTION GRADE REVIEW",0.018,0.074,"MATERIAL",log)!=null)notes++;if(AddNote(doc,"P004 SLIP FIT IN P003; FULL-LENGTH INTERFERENCE FIT PROHIBITED.",0.018,0.062,"GUIDE_FIT",log)!=null)notes++;if(AddNote(doc,"P003 SEAT Ø6.60 / P004 OD Ø6.54 = 0.06 NOMINAL DIAMETRAL CLEARANCE; FUNCTIONAL BAND 0.04...0.08.",0.018,0.050,"CLEARANCE",log)!=null)notes++;if(AddNote(doc,"P014 RETAINS AXIALLY; NO ADHESIVE; NO AXIAL PRELOAD.",0.018,0.038,"RETENTION",log)!=null)notes++;if(AddNote(doc,"PRODUCTION TOLERANCES / FUNCTIONAL SURFACE TEXTURE OPEN - DO NOT INFER.",0.018,0.026,"OPEN_PD",log)!=null)notes++;if(AddNote(doc,"ENGINEERING REVIEW - NOT FOR MANUFACTURE",0.218,0.074,"RELEASE_STATE",log)!=null)notes++;
            HideSheetNoteContaining(dr,"DEBURR AND",log);
            doc.ClearSelection2(true);doc.ForceRebuild3(false);doc.ViewZoomtofit2();doc.WindowRedraw();SaveAs(doc,dwg);SaveAs(doc,pdf);doc.ViewZoomtofit2();bool bmpOk=doc.SaveBMP(bmp,1800,1273);
            string title=doc.GetTitle();try{sw.CloseDoc(title);}catch{}doc=null;string ptitle=part.GetTitle();try{sw.CloseDoc(ptitle);}catch{}part=null;string after=Sha(partPath);Need(Eq(psha,after),"SOURCE CAD MUTATION DETECTED");
            bool dims=dl!=null&&did!=null&&dod!=null;string status=(dims&&notes==6)?"PASS_D004_ISO_EXEMPLAR_V1__RELEASE_HOLD":"PARTIAL_D004_ISO_EXEMPLAR_V1__RELEASE_HOLD";
            var sb=new StringBuilder();sb.AppendLine("SCHEMA=k01.d004_iso_exemplar_report.v1");sb.AppendLine("STATUS="+status);sb.AppendLine("DRAWING=K01-D-004");sb.AppendLine("PART=K01-P-004");sb.AppendLine("SOURCE_MODEL="+partPath);sb.AppendLine("SOURCE_SHA256_BEFORE="+psha);sb.AppendLine("SOURCE_SHA256_AFTER="+after);sb.AppendLine("SOURCE_INVARIANCE=PASS");sb.AppendLine("CANDIDATE_ROOT="+cand);sb.AppendLine("GENERATED_DIR="+generated);sb.AppendLine("MANUAL_FINISH_DIR="+manual);sb.AppendLine("EVIDENCE_DIR="+evidence);sb.AppendLine("OUTPUT_DRAWING="+dwg);sb.AppendLine("OUTPUT_PDF="+pdf);sb.AppendLine("OUTPUT_BMP="+bmp);sb.AppendLine("BMP_OK="+bmpOk);sb.AppendLine("VIEWS=2/2");sb.AppendLine("VIEW_PLAN=LONGITUDINAL_MODEL_VIEW+END_VIEW");sb.AppendLine("SHEET_SCALE=10:1");sb.AppendLine("FIRST_ANGLE=True");sb.AppendLine("CONTROLLED_DIMENSIONS="+(dims?"3/3":"PARTIAL"));sb.AppendLine("PRECISION_GUIDE_ID=3");sb.AppendLine("NOTES="+notes+"/6");sb.AppendLine("PRESENTATION_STATUS=HOLD_D8_VISUAL_REVIEW");sb.AppendLine("RELEASE=HOLD_PRODUCT_DEFINITION");sb.AppendLine("LOG_BEGIN");foreach(string z in log)sb.AppendLine(z);sb.AppendLine("LOG_END");Directory.CreateDirectory(Path.GetDirectoryName(report));File.WriteAllText(report,sb.ToString(),Encoding.UTF8);File.WriteAllText(Path.Combine(evidence,"semantic_report.txt"),sb.ToString(),Encoding.UTF8);
            Console.WriteLine("STATUS: "+status);Console.WriteLine("OVERALL: HOLD_D8_VISUAL_REVIEW");Console.WriteLine("SOURCE CAD INVARIANCE: PASS");Console.WriteLine("VIEWS: LONGITUDINAL MODEL VIEW + END VIEW");Console.WriteLine("SCALE: 10:1 | FIRST ANGLE");Console.WriteLine("DIMENSIONS: "+(dims?"3 / 3":"PARTIAL")+" | Ø5.055 precision=3");Console.WriteLine("DRAWING: "+dwg);Console.WriteLine("PDF: "+pdf);Console.WriteLine("REPORT: "+report);Console.WriteLine("NEXT: visual D8 check against D003/D006 golden level; release remains HOLD.");
            if(created&&sw!=null){try{sw.ExitApp();}catch{}}return status.StartsWith("PASS_")?0:3;
        }
        catch(Exception ex){try{File.WriteAllText(report,"STATUS=HOLD_D004_ISO_EXEMPLAR_V1\nERROR="+ex.ToString()+"\n",Encoding.UTF8);}catch{}Console.Error.WriteLine(ex.ToString());try{if(doc!=null&&sw!=null)sw.CloseDoc(doc.GetTitle());}catch{}try{if(part!=null&&sw!=null)sw.CloseDoc(part.GetTitle());}catch{}try{if(created&&sw!=null)sw.ExitApp();}catch{}return 2;}
    }
}
